package com.zephyr.croj.contest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@JdbcTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:contest-registration;MODE=MySQL;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Sql(statements = {
        "DROP TABLE IF EXISTS t_contest_registration",
        "DROP TABLE IF EXISTS t_contest",
        "DROP TABLE IF EXISTS t_user",
        "CREATE TABLE t_user (id BIGINT PRIMARY KEY, status INT NOT NULL, is_deleted INT NOT NULL)",
        "CREATE TABLE t_contest (id BIGINT PRIMARY KEY, title VARCHAR(255) NOT NULL, description_markdown CLOB, rule_type VARCHAR(16) NOT NULL, visibility VARCHAR(16) NOT NULL, lifecycle VARCHAR(16) NOT NULL, registration_opens_at TIMESTAMP NOT NULL, registration_closes_at TIMESTAMP NOT NULL, starts_at TIMESTAMP NOT NULL, freeze_at TIMESTAMP, ends_at TIMESTAMP NOT NULL, created_by BIGINT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE t_contest_registration (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, contest_id BIGINT NOT NULL, user_id BIGINT NOT NULL, status VARCHAR(16) NOT NULL, registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, managed_by BIGINT, UNIQUE(contest_id,user_id))",
        "INSERT INTO t_contest VALUES (1,'Public ACM','d','ACM','PUBLIC','PUBLISHED','2026-07-01 00:00:00','2026-07-09 00:00:00','2026-07-10 00:00:00','2026-07-10 01:30:00','2026-07-10 02:00:00',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",
        "INSERT INTO t_contest VALUES (2,'Private ACM','d','ACM','PRIVATE','PUBLISHED','2026-07-01 00:00:00','2026-07-09 00:00:00','2026-07-10 00:00:00',NULL,'2026-07-10 02:00:00',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",
        "INSERT INTO t_user VALUES (7,0,0),(8,1,0)",
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class ContestRegistrationIntegrationTest {
    @Autowired private JdbcTemplate jdbc;
    private ContestService service;

    @BeforeEach
    void setUp() {
        service = new ContestService(
                new ContestRepository(jdbc),
                Clock.fixed(Instant.parse("2026-07-05T00:00:00Z"), ZoneOffset.UTC));
    }

    @Test
    void duplicateConcurrentPublicRegistrationCreatesOneActiveRosterEntry() throws Exception {
        CountDownLatch start = new CountDownLatch(1);
        ExecutorService pool = Executors.newFixedThreadPool(2);
        try {
            List<java.util.concurrent.Future<String>> calls = List.of(
                    pool.submit(() -> { start.await(); return service.register(1L, 7L); }),
                    pool.submit(() -> { start.await(); return service.register(1L, 7L); }));
            start.countDown();
            assertEquals(List.of("REGISTERED", "REGISTERED"),
                    calls.stream().map(future -> await(future)).toList());
        } finally {
            pool.shutdownNow();
        }

        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_contest_registration WHERE contest_id=1 AND user_id=7 AND status='REGISTERED'",
                Integer.class));
    }

    @Test
    void privateContestRejectsSelfRegistration() {
        assertThrows(ContestApiException.class, () -> service.register(2L, 7L));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM t_contest_registration", Integer.class));
    }

    @Test
    void disabledUserCannotSelfRegisterWithAnOldToken() {
        assertThrows(ContestApiException.class, () -> service.register(1L, 8L));
        assertEquals(0, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_contest_registration WHERE user_id=8", Integer.class));
    }

    @Test
    void publicListCapsPageSizeAtOneHundred() {
        assertEquals(100, service.listPublic(1, 500).size());
    }

    private String await(java.util.concurrent.Future<String> future) {
        try {
            return future.get(5, TimeUnit.SECONDS);
        } catch (Exception exception) {
            throw new AssertionError(exception);
        }
    }
}
