package com.zephyr.croj.contest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.jdbc.Sql;

@JdbcTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:contest-content;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Sql(statements = {
        "DROP TABLE IF EXISTS t_contest_clarification_reply",
        "DROP TABLE IF EXISTS t_contest_clarification",
        "DROP TABLE IF EXISTS t_contest_scoreboard_snapshot",
        "DROP TABLE IF EXISTS t_submission",
        "DROP TABLE IF EXISTS t_contest_problem",
        "DROP TABLE IF EXISTS t_contest_registration",
        "DROP TABLE IF EXISTS t_contest",
        "CREATE TABLE t_contest (id BIGINT PRIMARY KEY, title VARCHAR(255), description_markdown CLOB, rule_type VARCHAR(16), visibility VARCHAR(16), lifecycle VARCHAR(16), registration_opens_at TIMESTAMP, registration_closes_at TIMESTAMP, starts_at TIMESTAMP, freeze_at TIMESTAMP, ends_at TIMESTAMP, created_by BIGINT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE t_contest_registration (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, contest_id BIGINT, user_id BIGINT, status VARCHAR(16), registered_at TIMESTAMP, updated_at TIMESTAMP, managed_by BIGINT, UNIQUE(contest_id,user_id))",
        "CREATE TABLE t_contest_problem (contest_id BIGINT, problem_id BIGINT, problem_version_id BIGINT, label VARCHAR(16), score INT, PRIMARY KEY(contest_id,problem_id))",
        "CREATE TABLE t_submission (id BIGINT PRIMARY KEY, problem_id BIGINT, problem_version_id BIGINT, contest_id BIGINT, user_id BIGINT, language VARCHAR(20), `code` CLOB, status INT, create_time TIMESTAMP, update_time TIMESTAMP, is_deleted INT DEFAULT 0)",
        "CREATE TABLE t_contest_clarification (id BIGINT PRIMARY KEY, contest_id BIGINT, problem_id BIGINT, asked_by BIGINT, question_markdown CLOB, status VARCHAR(16), created_at TIMESTAMP)",
        "CREATE TABLE t_contest_clarification_reply (id BIGINT PRIMARY KEY, clarification_id BIGINT, reply_markdown CLOB, replied_by BIGINT, is_public BOOLEAN, created_at TIMESTAMP)",
        "CREATE TABLE t_contest_scoreboard_snapshot (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, contest_id BIGINT, view_type VARCHAR(16), cutoff_at TIMESTAMP, source_version VARCHAR(160), payload JSON, generated_at TIMESTAMP, UNIQUE(contest_id,view_type,cutoff_at))",
        "INSERT INTO t_contest VALUES (1,'Weekly','d','ACM','PUBLIC','PUBLISHED','2026-07-01 00:00:00','2026-07-09 00:00:00','2026-07-10 10:00:00','2026-07-10 11:00:00','2026-07-10 12:00:00',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",
        "INSERT INTO t_contest_registration(contest_id,user_id,status) VALUES (1,7,'REGISTERED'),(1,8,'REGISTERED')",
        "INSERT INTO t_contest_problem VALUES (1,42,101,'A',100)",
        "INSERT INTO t_submission VALUES (1,42,101,1,7,'java','x',3,'2026-07-10 10:10:00','2026-07-10 10:10:01',0)",
        "INSERT INTO t_submission VALUES (2,42,101,1,7,'java','x',1,'2026-07-10 10:30:00','2026-07-10 10:30:01',0)",
        "INSERT INTO t_submission VALUES (3,42,101,1,8,'java','x',1,'2026-07-10 11:00:00','2026-07-10 11:00:01',0)",
        "INSERT INTO t_contest_clarification VALUES (10,1,42,7,'Is input sorted?','ANSWERED','2026-07-10 10:15:00')",
        "INSERT INTO t_contest_clarification_reply VALUES (20,10,'private details',9,FALSE,'2026-07-10 10:16:00')",
        "INSERT INTO t_contest_clarification_reply VALUES (21,10,'No.',9,TRUE,'2026-07-10 10:17:00')"
})
class ContestContentAndScoreboardIntegrationTest {
    @Autowired private JdbcTemplate jdbc;

    @Test
    void problemsStayHiddenUntilStartEvenForRegisteredUsers() {
        ContestRepository repository = new ContestRepository(jdbc);
        ContestService before = serviceAt(repository, "2026-07-10T09:59:59Z");
        assertThrows(ContestApiException.class, () -> before.problems(1L, 7L, false));

        ContestService running = serviceAt(repository, "2026-07-10T10:00:00Z");
        assertEquals(42L, running.problems(1L, 7L, false).get(0).problemId());
    }

    @Test
    void privateClarificationReplyIsOnlyVisibleToAskerOrAdministrator() {
        ContestRepository repository = new ContestRepository(jdbc);
        ContestService running = serviceAt(repository, "2026-07-10T10:30:00Z");

        assertEquals(2, running.clarifications(1L, 7L, false).get(0).replies().size());
        assertEquals(1, running.clarifications(1L, 8L, false).get(0).replies().size());
        assertEquals("No.", running.clarifications(1L, 8L, false).get(0).replies().get(0).replyMarkdown());
    }

    @Test
    void frozenPublicBoardUsesExclusiveFreezeCutoffWhileAdminRemainsLive() {
        ContestRepository repository = new ContestRepository(jdbc);
        Clock frozenClock = fixed("2026-07-10T11:30:00Z");
        ContestScoreboardService scoreboards = new ContestScoreboardService(repository, frozenClock);

        var publicBoard = scoreboards.publicScoreboard(1L, 7L);
        assertEquals(1, publicBoard.rows().get(0).solved());
        assertEquals(0, publicBoard.rows().get(1).solved());
        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_contest_scoreboard_snapshot WHERE contest_id=1",
                Integer.class));

        var adminBoard = scoreboards.administratorScoreboard(1L);
        assertEquals(2, adminBoard.rows().size());
        assertEquals(1, adminBoard.rows().get(1).solved());
    }

    private ContestService serviceAt(ContestRepository repository, String instant) {
        return new ContestService(repository, fixed(instant));
    }

    private Clock fixed(String instant) {
        return Clock.fixed(Instant.parse(instant), ZoneOffset.UTC);
    }
}
