package com.zephyr.croj.contest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.jdbc.Sql;

@JdbcTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:contest-content;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Sql(statements = {
        "SET TIME ZONE 'UTC'",
        "DROP TABLE IF EXISTS t_contest_clarification_reply",
        "DROP TABLE IF EXISTS t_contest_clarification",
        "DROP TABLE IF EXISTS t_contest_scoreboard_snapshot",
        "DROP TABLE IF EXISTS t_submission",
        "DROP TABLE IF EXISTS t_contest_problem",
        "DROP TABLE IF EXISTS t_problem_version",
        "DROP TABLE IF EXISTS t_contest_registration",
        "DROP TABLE IF EXISTS t_contest",
        "DROP TABLE IF EXISTS t_user",
        "CREATE TABLE t_user (id BIGINT PRIMARY KEY, username VARCHAR(50) NOT NULL)",
        "CREATE TABLE t_contest (id BIGINT PRIMARY KEY, title VARCHAR(255), description_markdown CLOB, rule_type VARCHAR(16), visibility VARCHAR(16), lifecycle VARCHAR(16), registration_opens_at TIMESTAMP, registration_closes_at TIMESTAMP, starts_at TIMESTAMP, freeze_at TIMESTAMP, ends_at TIMESTAMP, created_by BIGINT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE t_contest_registration (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, contest_id BIGINT, user_id BIGINT, status VARCHAR(16), registered_at TIMESTAMP, updated_at TIMESTAMP, managed_by BIGINT, UNIQUE(contest_id,user_id))",
        "CREATE TABLE t_contest_problem (contest_id BIGINT, problem_id BIGINT, problem_version_id BIGINT, label VARCHAR(16), score INT, PRIMARY KEY(contest_id,problem_id))",
        "CREATE TABLE t_problem_version (id BIGINT PRIMARY KEY, problem_id BIGINT, state VARCHAR(20), statement_json CLOB, limits_json CLOB, judge_config_json CLOB)",
        "CREATE TABLE t_submission (id BIGINT PRIMARY KEY, problem_id BIGINT, problem_version_id BIGINT, contest_id BIGINT, user_id BIGINT, language VARCHAR(20), `code` CLOB, status INT, score INT, create_time TIMESTAMP, update_time TIMESTAMP, is_deleted INT DEFAULT 0)",
        "CREATE TABLE t_contest_clarification (id BIGINT PRIMARY KEY, contest_id BIGINT, problem_id BIGINT, asked_by BIGINT, question_markdown CLOB, status VARCHAR(16), created_at TIMESTAMP)",
        "CREATE TABLE t_contest_clarification_reply (id BIGINT PRIMARY KEY, clarification_id BIGINT, reply_markdown CLOB, replied_by BIGINT, is_public BOOLEAN, created_at TIMESTAMP)",
        "CREATE TABLE t_contest_scoreboard_snapshot (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, contest_id BIGINT, view_type VARCHAR(16), cutoff_at TIMESTAMP, source_version VARCHAR(160), payload JSON, generated_at TIMESTAMP, UNIQUE(contest_id,view_type,cutoff_at))",
        "INSERT INTO t_contest VALUES (1,'Weekly','d','ACM','PUBLIC','PUBLISHED','2026-07-01 00:00:00','2026-07-09 00:00:00','2026-07-10 10:00:00','2026-07-10 11:00:00','2026-07-10 12:00:00',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",
        "INSERT INTO t_contest VALUES (2,'OI Weekly','d','OI','PUBLIC','PUBLISHED','2026-07-01 00:00:00','2026-07-09 00:00:00','2026-07-10 10:00:00','2026-07-10 11:00:00','2026-07-10 12:00:00',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",
        "INSERT INTO t_user VALUES (7,'alice'),(8,'bob'),(9,'carol'),(17,'dave'),(18,'erin')",
        "INSERT INTO t_contest_registration(contest_id,user_id,status) VALUES (1,7,'REGISTERED'),(1,8,'REGISTERED')",
        "INSERT INTO t_contest_registration(contest_id,user_id,status) VALUES (2,17,'REGISTERED'),(2,18,'REGISTERED')",
        "INSERT INTO t_contest_problem VALUES (1,42,101,'A',100)",
        "INSERT INTO t_contest_problem VALUES (2,52,102,'A',100)",
        "INSERT INTO t_problem_version VALUES (101,42,'PUBLISHED','{\"title\":\"Pinned contest statement\"}','{\"timeMs\":1000}','{\"checker\":\"standard\"}')",
        "INSERT INTO t_problem_version VALUES (102,52,'PUBLISHED','{\"title\":\"Pinned OI statement\"}','{\"timeMs\":1000}','{\"checker\":\"standard\"}')",
        "INSERT INTO t_submission VALUES (1,42,101,1,7,'java','x',3,NULL,'2026-07-10 10:10:00','2026-07-10 10:10:01',0)",
        "INSERT INTO t_submission VALUES (2,42,101,1,7,'java','x',1,NULL,'2026-07-10 10:30:00','2026-07-10 10:30:01',0)",
        "INSERT INTO t_submission VALUES (3,42,101,1,8,'java','x',1,NULL,'2026-07-10 11:00:00','2026-07-10 11:00:01',0)",
        "INSERT INTO t_submission VALUES (4,52,102,2,17,'java','x',3,60,'2026-07-10 10:10:00','2026-07-10 10:10:01',0)",
        "INSERT INTO t_submission VALUES (5,52,102,2,17,'java','x',3,90,'2026-07-10 10:50:00','2026-07-10 10:50:01',0)",
        "INSERT INTO t_submission VALUES (6,52,102,2,18,'java','x',3,90,'2026-07-10 10:40:00','2026-07-10 10:40:01',0)",
        "INSERT INTO t_submission VALUES (7,52,102,2,17,'java','x',1,100,'2026-07-10 11:10:00','2026-07-10 11:10:01',0)",
        "INSERT INTO t_contest_clarification VALUES (10,1,42,7,'Is input sorted?','ANSWERED','2026-07-10 10:15:00')",
        "INSERT INTO t_contest_clarification_reply VALUES (20,10,'private details',9,FALSE,'2026-07-10 10:16:00')",
        "INSERT INTO t_contest_clarification_reply VALUES (21,10,'No.',9,TRUE,'2026-07-10 10:17:00')"
})
class ContestContentAndScoreboardIntegrationTest {
    @Autowired private JdbcTemplate jdbc;

    @Test
    void problemsStayHiddenUntilStartEvenForRegisteredUsers() {
        ContestRepository repository = new ContestRepository(jdbc);
        ContestService before = serviceAt(repository, "2026-07-10T09:59:59Z");
        assertThrows(ContestApiException.class, () -> before.problems(1L, 7L, false));

        ContestService running = serviceAt(repository, "2026-07-10T10:00:00Z");
        var problem = running.problems(1L, 7L, false).get(0);
        assertEquals(42L, problem.problemId());
        assertEquals("{\"title\":\"Pinned contest statement\"}", problem.statementJson());
        assertEquals("{\"timeMs\":1000}", problem.limitsJson());
    }

    @Test
    void privateClarificationReplyIsOnlyVisibleToAskerOrAdministrator() {
        ContestRepository repository = new ContestRepository(jdbc);
        ContestService running = serviceAt(repository, "2026-07-10T10:30:00Z");

        assertEquals(2, running.clarifications(1L, 7L, false).get(0).replies().size());
        assertEquals(1, running.clarifications(1L, 8L, false).get(0).replies().size());
        assertEquals("No.", running.clarifications(1L, 8L, false).get(0).replies().get(0).replyMarkdown());
    }

    @Test
    void frozenPublicBoardUsesExclusiveFreezeCutoffWhileAdminRemainsLive() {
        ContestRepository repository = new ContestRepository(jdbc);
        Clock frozenClock = fixed("2026-07-10T11:30:00Z");
        ContestScoreboardService scoreboards = new ContestScoreboardService(repository, frozenClock);

        var publicBoard = scoreboards.publicScoreboard(1L, 7L);
        assertEquals(1, publicBoard.rows().get(0).solved());
        assertEquals(0, publicBoard.rows().get(1).solved());
        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_contest_scoreboard_snapshot WHERE contest_id=1",
                Integer.class));
        jdbc.update("INSERT INTO t_contest_registration(contest_id,user_id,status) VALUES (1,9,'REGISTERED')");
        var refreshedPublicBoard = scoreboards.publicScoreboard(1L, 7L);
        assertEquals(3, refreshedPublicBoard.rows().size());
        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_contest_scoreboard_snapshot WHERE contest_id=1",
                Integer.class));

        var adminBoard = scoreboards.administratorScoreboard(1L);
        assertEquals(3, adminBoard.rows().size());
        assertEquals(1, adminBoard.rows().get(1).solved());
    }

    @Test
    void oiBoardUsesBestPinnedScoresAndKeepsPostFreezeResultsPrivate() {
        ContestRepository repository = new ContestRepository(jdbc);
        Clock frozenClock = fixed("2026-07-10T11:30:00Z");
        ContestScoreboardService scoreboards = new ContestScoreboardService(repository, frozenClock);

        var publicBoard = scoreboards.publicScoreboard(2L, 17L);
        assertEquals("OI", publicBoard.ruleType());
        assertEquals(100, publicBoard.maximumScore());
        assertEquals(18L, publicBoard.rows().get(0).userId());
        assertEquals("erin", publicBoard.rows().get(0).username());
        assertEquals(90, publicBoard.rows().get(0).totalScore());
        assertEquals(17L, publicBoard.rows().get(1).userId());
        assertEquals(90, publicBoard.rows().get(1).totalScore());
        assertEquals(5L, publicBoard.rows().get(1).problems().get(0).submissionId());
        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_contest_scoreboard_snapshot WHERE contest_id=2",
                Integer.class));
        jdbc.update(
                "UPDATE t_contest_scoreboard_snapshot SET generated_at='2000-01-01 00:00:00' WHERE contest_id=2");
        var cachedPublicBoard = scoreboards.publicScoreboard(2L, 17L);
        assertEquals(18L, cachedPublicBoard.rows().get(0).userId());
        assertEquals(90, cachedPublicBoard.rows().get(0).totalScore());
        assertEquals(2000, jdbc.queryForObject(
                        "SELECT YEAR(generated_at) FROM t_contest_scoreboard_snapshot WHERE contest_id=2",
                        Integer.class));

        var adminBoard = scoreboards.administratorScoreboard(2L);
        assertEquals(17L, adminBoard.rows().get(0).userId());
        assertEquals(100, adminBoard.rows().get(0).totalScore());
        assertEquals(7L, adminBoard.rows().get(0).problems().get(0).submissionId());
    }

    @Test
    void oiScoreChangeInvalidatesStableSnapshotSourceVersion() {
        ContestRepository repository = new ContestRepository(jdbc);
        Instant cutoff = Instant.parse("2026-07-10T11:00:00Z");
        String before = repository.scoreboardSourceVersion(2L, cutoff);

        jdbc.update("UPDATE t_submission SET score=95 WHERE id=5");

        String after = repository.scoreboardSourceVersion(2L, cutoff);
        assertNotEquals(before, after);
    }

    @Test
    void participantRenameInvalidatesStableSnapshotSourceVersion() {
        ContestRepository repository = new ContestRepository(jdbc);
        Instant cutoff = Instant.parse("2026-07-10T11:00:00Z");
        String before = repository.scoreboardSourceVersion(2L, cutoff);

        jdbc.update("UPDATE t_user SET username='renamed' WHERE id=18");

        String after = repository.scoreboardSourceVersion(2L, cutoff);
        assertNotEquals(before, after);
    }

    @Test
    void sourceVersionCannotCollideWhenRegistrationStatusesAreSwapped() {
        ContestRepository repository = new ContestRepository(jdbc);
        jdbc.update("INSERT INTO t_contest_registration(contest_id,user_id,status,updated_at) VALUES (1,9,'CANCELLED','2026-07-10 10:00:00')");
        jdbc.update("UPDATE t_contest_registration SET updated_at='2026-07-10 10:00:00' WHERE contest_id=1");
        String before = repository.scoreboardSourceVersion(1L, Instant.parse("2026-07-10T11:00:00Z"));

        jdbc.update("UPDATE t_contest_registration SET status=CASE user_id WHEN 7 THEN 'CANCELLED' WHEN 9 THEN 'REGISTERED' ELSE status END WHERE contest_id=1 AND user_id IN (7,9)");

        String after = repository.scoreboardSourceVersion(1L, Instant.parse("2026-07-10T11:00:00Z"));
        assertNotEquals(before, after);
    }

    @Test
    void sourceVersionCannotCollideWhenSubmissionStatusesAreSwapped() {
        ContestRepository repository = new ContestRepository(jdbc);
        jdbc.update("UPDATE t_submission SET update_time='2026-07-10 10:40:00' WHERE contest_id=1");
        String before = repository.scoreboardSourceVersion(1L, Instant.parse("2026-07-10T11:00:00Z"));

        jdbc.update("UPDATE t_submission SET status=CASE id WHEN 1 THEN 1 WHEN 2 THEN 3 ELSE status END WHERE id IN (1,2)");

        String after = repository.scoreboardSourceVersion(1L, Instant.parse("2026-07-10T11:00:00Z"));
        assertNotEquals(before, after);
    }

    private ContestService serviceAt(ContestRepository repository, String instant) {
        return new ContestService(repository, fixed(instant));
    }

    private Clock fixed(String instant) {
        return Clock.fixed(Instant.parse(instant), ZoneOffset.UTC);
    }
}
