server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: coderush-oj
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_rush_oj?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: admin
    password: admin123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.zephyr.croj.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

logging:
  level:
    com.zephyr.croj: info
    org.springframework: warn

# JWT配置
jwt:
  secret: ${JWT_SECRET:coderushojsecretkey123456789987654321}
  expiration: 86400000  # 24小时
  header: Authorization
  tokenPrefix: Bearer

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true