server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: coderush-oj
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_rush_oj?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: admin
    password: admin123
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    username: your username
    password: your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.zephyr.croj.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

logging:
  level:
    com.zephyr.croj: info
    org.springframework: warn

# JWT配置
jwt:
  secret: ${JWT_SECRET:coderushojsecretkey123456789987654321}
  expiration: 86400000  # 24小时
  header: Authorization
  tokenPrefix: Bearer

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

# Application specific configuration
app:
  upload:
    dir: uploads  # Root directory for file uploads
    avatar:
      dir: avatar  # Subdirectory for avatar images
  domain: http://localhost:8080  # Your application domain for file URLs
  frontend-url: http://localhost:3000