package com.zephyr.croj.bootstrap;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.sql.DataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.transaction.support.TransactionTemplate;

class AdminBootstrapServiceTest {

    private EmbeddedDatabase database;
    private JdbcTemplate jdbc;
    private BCryptPasswordEncoder passwords;
    private AdminBootstrapService service;

    @BeforeEach
    void setUp() {
        database = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .setName("admin-bootstrap-" + System.nanoTime() + ";MODE=MySQL;DB_CLOSE_DELAY=-1")
                .build();
        jdbc = new JdbcTemplate(database);
        jdbc.execute("""
                CREATE TABLE t_system_bootstrap_lock (
                  name VARCHAR(64) PRIMARY KEY,
                  administrator_id BIGINT,
                  administrator_username VARCHAR(50),
                  administrator_email VARCHAR(100),
                  claimed_at TIMESTAMP,
                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.update("INSERT INTO t_system_bootstrap_lock(name) VALUES (?)", "first-super-admin");
        jdbc.execute("""
                CREATE TABLE t_user (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  username VARCHAR(50) NOT NULL UNIQUE,
                  password VARCHAR(100) NOT NULL,
                  email VARCHAR(100) NOT NULL UNIQUE,
                  role TINYINT NOT NULL,
                  status TINYINT NOT NULL,
                  email_verified TINYINT NOT NULL,
                  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  is_deleted TINYINT NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE TABLE t_audit_log (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  actor_id BIGINT,
                  action VARCHAR(128) NOT NULL,
                  resource_type VARCHAR(64) NOT NULL,
                  resource_id VARCHAR(128),
                  metadata JSON,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        passwords = new BCryptPasswordEncoder(4);
        service = newService(database);
    }

    @AfterEach
    void tearDown() {
        database.shutdown();
    }

    @Test
    void createsOneEnabledVerifiedSuperAdminWithHashedPassword() {
        AdminBootstrapResult result = service.bootstrap(request("Correct-Horse-Battery-Staple!"));

        assertEquals(AdminBootstrapResult.CREATED, result);
        assertEquals(1, countUsers());
        assertEquals(2, jdbc.queryForObject("SELECT role FROM t_user", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT status FROM t_user", Integer.class));
        assertEquals(1, jdbc.queryForObject("SELECT email_verified FROM t_user", Integer.class));
        String hash = jdbc.queryForObject("SELECT password FROM t_user", String.class);
        assertTrue(passwords.matches("Correct-Horse-Battery-Staple!", hash));
        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_audit_log WHERE action = 'SYSTEM_BOOTSTRAP_SUPER_ADMIN'",
                Integer.class));
        assertEquals(1L, jdbc.queryForObject(
                "SELECT administrator_id FROM t_system_bootstrap_lock WHERE name = 'first-super-admin'",
                Long.class));
        assertEquals("admin", jdbc.queryForObject(
                "SELECT administrator_username FROM t_system_bootstrap_lock WHERE name = 'first-super-admin'",
                String.class));
        assertEquals("admin@coderushoj.local", jdbc.queryForObject(
                "SELECT administrator_email FROM t_system_bootstrap_lock WHERE name = 'first-super-admin'",
                String.class));
    }

    @Test
    void exactIdentityReplayDoesNotRotatePasswordOrDuplicateAudit() {
        assertEquals(AdminBootstrapResult.CREATED, service.bootstrap(request("first-password-is-secret")));
        String originalHash = jdbc.queryForObject("SELECT password FROM t_user", String.class);

        assertEquals(AdminBootstrapResult.ALREADY_PRESENT, service.bootstrap(request("different-replay-secret")));

        assertEquals(1, countUsers());
        assertEquals(originalHash, jdbc.queryForObject("SELECT password FROM t_user", String.class));
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
    }

    @Test
    void aDifferentIdentityCannotReuseTheOneShotGuard() {
        service.bootstrap(request("first-password-is-secret"));
        String originalHash = jdbc.queryForObject("SELECT password FROM t_user", String.class);

        assertThrows(AdminBootstrapConflictException.class, () -> service.bootstrap(
                new AdminBootstrapRequest("other-admin", "other@coderushoj.local", "another-secret-value")));

        assertEquals(1, countUsers());
        assertEquals("admin", jdbc.queryForObject("SELECT username FROM t_user", String.class));
        assertEquals("admin@coderushoj.local", jdbc.queryForObject("SELECT email FROM t_user", String.class));
        assertEquals(originalHash, jdbc.queryForObject("SELECT password FROM t_user", String.class));
        assertEquals(2, jdbc.queryForObject("SELECT role FROM t_user", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT status FROM t_user", Integer.class));
        assertEquals(1, jdbc.queryForObject("SELECT email_verified FROM t_user", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT is_deleted FROM t_user", Integer.class));
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
    }

    @Test
    void concurrentBootstrapCreatesExactlyOneAdministrator() throws Exception {
        int callers = 8;
        ExecutorService pool = Executors.newFixedThreadPool(callers);
        CountDownLatch ready = new CountDownLatch(callers);
        CountDownLatch start = new CountDownLatch(1);
        List<Future<AdminBootstrapResult>> futures = new ArrayList<>();
        try {
            for (int index = 0; index < callers; index++) {
                futures.add(pool.submit(() -> {
                    ready.countDown();
                    start.await();
                    return newService(database).bootstrap(request("concurrent-secret-value"));
                }));
            }
            ready.await();
            start.countDown();

            List<AdminBootstrapResult> results = new ArrayList<>();
            for (Future<AdminBootstrapResult> future : futures) {
                results.add(future.get());
            }
            assertEquals(1, results.stream().filter(AdminBootstrapResult.CREATED::equals).count());
            assertEquals(callers - 1L, results.stream().filter(AdminBootstrapResult.ALREADY_PRESENT::equals).count());
            assertEquals(1, countUsers());
            assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
        } finally {
            pool.shutdownNow();
        }
    }

    @Test
    void concurrentDifferentIdentitiesCreateOnlyTheFirstAdministrator() throws Exception {
        int callers = 8;
        ExecutorService pool = Executors.newFixedThreadPool(callers);
        CountDownLatch ready = new CountDownLatch(callers);
        CountDownLatch start = new CountDownLatch(1);
        List<Future<AdminBootstrapResult>> futures = new ArrayList<>();
        try {
            for (int index = 0; index < callers; index++) {
                int identity = index;
                futures.add(pool.submit(() -> {
                    ready.countDown();
                    start.await();
                    return newService(database).bootstrap(new AdminBootstrapRequest(
                            "admin-" + identity,
                            "admin-" + identity + "@coderushoj.local",
                            "concurrent-secret-value"));
                }));
            }
            ready.await();
            start.countDown();

            int created = 0;
            int conflicts = 0;
            for (Future<AdminBootstrapResult> future : futures) {
                try {
                    if (future.get() == AdminBootstrapResult.CREATED) {
                        created++;
                    }
                } catch (ExecutionException failure) {
                    assertInstanceOf(AdminBootstrapConflictException.class, failure.getCause());
                    conflicts++;
                }
            }
            assertEquals(1, created);
            assertEquals(callers - 1, conflicts);
            assertEquals(1, countUsers());
            assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
            assertEquals(1, jdbc.queryForObject(
                    "SELECT COUNT(*) FROM t_system_bootstrap_lock WHERE administrator_id IS NOT NULL",
                    Integer.class));
        } finally {
            pool.shutdownNow();
        }
    }

    @Test
    void acceptsPasswordsAtTheBcryptUtf8ByteBoundary() {
        String password = "界".repeat(24);

        assertEquals(AdminBootstrapResult.CREATED, service.bootstrap(request(password)));

        String hash = jdbc.queryForObject("SELECT password FROM t_user", String.class);
        assertTrue(passwords.matches(password, hash));
    }

    @Test
    void rejectsPasswordsBeyondTheBcryptUtf8ByteBoundary() {
        assertThrows(IllegalArgumentException.class, () -> service.bootstrap(request("a".repeat(73))));
        assertThrows(IllegalArgumentException.class, () -> service.bootstrap(request("界".repeat(25))));
        assertEquals(0, countUsers());
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
    }

    @Test
    void keepsTheMinimumPasswordLengthAsACharacterRule() {
        assertThrows(IllegalArgumentException.class, () -> service.bootstrap(request("🔐".repeat(11))));
        assertEquals(AdminBootstrapResult.CREATED, service.bootstrap(request("🔐".repeat(12))));
    }

    @Test
    void anOrdinaryAccountConflictDoesNotMutateCredentialsOrPrivileges() {
        insertAccount("admin", "ordinary@coderushoj.local", "ordinary-hash", 0, 0, 0, 0);

        assertThrows(AdminBootstrapConflictException.class, () -> service.bootstrap(request("new-secret-value")));

        assertAccountUnchanged("admin", "ordinary@coderushoj.local", "ordinary-hash", 0, 0, 0, 0);
    }

    @Test
    void anOrdinaryEmailConflictDoesNotMutateCredentialsOrPrivileges() {
        insertAccount("ordinary", "admin@coderushoj.local", "ordinary-email-hash", 0, 0, 0, 0);

        assertThrows(AdminBootstrapConflictException.class, () -> service.bootstrap(request("new-secret-value")));

        assertAccountUnchanged("ordinary", "admin@coderushoj.local", "ordinary-email-hash", 0, 0, 0, 0);
    }

    @Test
    void aPreexistingActiveSuperAdministratorCannotClaimTheBootstrapGuard() {
        insertAccount("admin", "admin@coderushoj.local", "legacy-hash", 2, 0, 1, 0);

        assertThrows(AdminBootstrapConflictException.class, () -> service.bootstrap(request("new-secret-value")));

        assertAccountUnchanged("admin", "admin@coderushoj.local", "legacy-hash", 2, 0, 1, 0);
        assertEquals(0, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_system_bootstrap_lock WHERE administrator_id IS NOT NULL",
                Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
    }

    @Test
    void aDisabledSuperAdministratorConflictIsNotReactivated() {
        insertAccount("admin", "admin@coderushoj.local", "disabled-hash", 2, 1, 1, 0);

        assertThrows(AdminBootstrapConflictException.class, () -> service.bootstrap(request("new-secret-value")));

        assertAccountUnchanged("admin", "admin@coderushoj.local", "disabled-hash", 2, 1, 1, 0);
    }

    @Test
    void aSoftDeletedSuperAdministratorConflictIsNotRestored() {
        insertAccount("admin", "admin@coderushoj.local", "deleted-hash", 2, 0, 1, 1);

        assertThrows(AdminBootstrapConflictException.class, () -> service.bootstrap(request("new-secret-value")));

        assertAccountUnchanged("admin", "admin@coderushoj.local", "deleted-hash", 2, 0, 1, 1);
    }

    @Test
    void requestStringRepresentationNeverContainsIdentityOrPassword() {
        AdminBootstrapRequest request = request("plain-text-secret-value");

        assertTrue(!request.toString().contains("admin"));
        assertTrue(!request.toString().contains("admin@coderushoj.local"));
        assertTrue(!request.toString().contains("plain-text-secret-value"));
    }

    @Test
    void rejectsWeakOrMalformedBootstrapValuesBeforeOpeningTransaction() {
        assertThrows(IllegalArgumentException.class,
                () -> service.bootstrap(new AdminBootstrapRequest("a", "invalid", "short")));
        assertEquals(0, countUsers());
    }

    private AdminBootstrapService newService(DataSource dataSource) {
        JdbcTemplate template = new JdbcTemplate(dataSource);
        return new AdminBootstrapService(
                template,
                new TransactionTemplate(new DataSourceTransactionManager(dataSource)),
                passwords == null ? new BCryptPasswordEncoder(4) : passwords);
    }

    private AdminBootstrapRequest request(String password) {
        return new AdminBootstrapRequest("admin", "admin@coderushoj.local", password);
    }

    private int countUsers() {
        return jdbc.queryForObject("SELECT COUNT(*) FROM t_user", Integer.class);
    }

    private void insertAccount(
            String username,
            String email,
            String password,
            int role,
            int status,
            int emailVerified,
            int deleted) {
        jdbc.update(
                """
                INSERT INTO t_user
                    (username, password, email, role, status, email_verified, is_deleted)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                username,
                password,
                email,
                role,
                status,
                emailVerified,
                deleted);
    }

    private void assertAccountUnchanged(
            String username,
            String email,
            String password,
            int role,
            int status,
            int emailVerified,
            int deleted) {
        assertEquals(1, countUsers());
        assertEquals(username, jdbc.queryForObject("SELECT username FROM t_user", String.class));
        assertEquals(email, jdbc.queryForObject("SELECT email FROM t_user", String.class));
        assertEquals(password, jdbc.queryForObject("SELECT password FROM t_user", String.class));
        assertEquals(role, jdbc.queryForObject("SELECT role FROM t_user", Integer.class));
        assertEquals(status, jdbc.queryForObject("SELECT status FROM t_user", Integer.class));
        assertEquals(emailVerified, jdbc.queryForObject("SELECT email_verified FROM t_user", Integer.class));
        assertEquals(deleted, jdbc.queryForObject("SELECT is_deleted FROM t_user", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM t_audit_log", Integer.class));
        assertEquals(0, jdbc.queryForObject(
                "SELECT COUNT(*) FROM t_system_bootstrap_lock WHERE administrator_id IS NOT NULL",
                Integer.class));
    }
}
