package com.zephyr.croj.judge;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.zephyr.croj.common.exception.JudgeResultConflictException;
import com.zephyr.croj.model.dto.JudgeResultRequest;
import com.zephyr.croj.service.JudgeResultService;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.apache.rocketmq.spring.core.RocketMQTemplate;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.jdbc.Sql;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:judge-result;MODE=MySQL;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false",
        "spring.autoconfigure.exclude=org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration",
        "springdoc.api-docs.enabled=false",
        "springdoc.swagger-ui.enabled=false",
        "spring.data.redis.password=test-only",
        "spring.mail.password=test-only",
        "jwt.secret=test-only-secret-with-at-least-32-bytes",
        "app.judge-result.service-token=judge-result-test-token-with-32-bytes",
        "app.upload.base-dir=target/test-uploads",
        "app.outbox.enabled=false",
})
@Sql(statements = {
        "DROP TABLE IF EXISTS t_judge_result_receipt",
        "DROP TABLE IF EXISTS t_judge_attempt",
        "DROP TABLE IF EXISTS t_submission",
        "DROP TABLE IF EXISTS t_problem_version",
        "DROP TABLE IF EXISTS t_problem",
        "CREATE TABLE t_problem (id BIGINT PRIMARY KEY, accepted_count INT NOT NULL DEFAULT 0)",
        "CREATE TABLE t_problem_version (id BIGINT PRIMARY KEY, problem_id BIGINT NOT NULL, version_no INT, state VARCHAR(32), statement_json CLOB, limits_json CLOB, judge_config_json CLOB, created_by BIGINT, created_at TIMESTAMP, published_at TIMESTAMP, projection_complete BOOLEAN NOT NULL)",
        "CREATE TABLE t_submission (id BIGINT PRIMARY KEY, problem_id BIGINT NOT NULL, problem_version_id BIGINT NOT NULL, contest_id BIGINT, user_id BIGINT NOT NULL, language VARCHAR(20) NOT NULL, `code` CLOB NOT NULL, status INT NOT NULL, run_time INT, memory INT, judge_info JSON, score INT, error_message CLOB, create_time TIMESTAMP, update_time TIMESTAMP, is_deleted INT NOT NULL DEFAULT 0)",
        "CREATE TABLE t_judge_attempt (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, submission_id BIGINT NOT NULL, attempt_no INT NOT NULL, job_name VARCHAR(128), runner_image VARCHAR(255), status VARCHAR(32) NOT NULL, result_json JSON, started_at TIMESTAMP, finished_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE (submission_id, attempt_no))",
        "CREATE TABLE t_judge_result_receipt (result_id VARCHAR(128) PRIMARY KEY, submission_id BIGINT NOT NULL, attempt_no INT NOT NULL, payload_sha256 CHAR(64) NOT NULL, final_status VARCHAR(32) NOT NULL, received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
        "INSERT INTO t_problem (id, accepted_count) VALUES (42, 0)",
        "INSERT INTO t_problem_version (id, problem_id, version_no, state, limits_json, judge_config_json, projection_complete) VALUES (101, 42, 1, 'PUBLISHED', '{\"timeLimit\":1000,\"memoryLimit\":64,\"totalScore\":100}', '{\"specialJudge\":false,\"specialJudgeCode\":null,\"specialJudgeLanguage\":null,\"judgeMode\":0}', TRUE)",
        "INSERT INTO t_submission (id, problem_id, problem_version_id, user_id, language, `code`, status, is_deleted) VALUES (99, 42, 101, 7, 'java17', 'class Main {}', 0, 0)",
        "INSERT INTO t_judge_attempt (submission_id, attempt_no, status) VALUES (99, 1, 'QUEUED')",
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class JudgeResultTransactionIntegrationTest {
    @Autowired private JudgeResultService results;
    @Autowired private JdbcTemplate jdbc;
    @Autowired private ObjectMapper objectMapper;
    @MockitoBean private RocketMQTemplate rocketMq;

    @Test
    void resultAndStatisticsCommitAtomicallyAndDuplicatesDoNotDoubleCount() {
        JudgeResultRequest request = accepted("result-1");

        assertEquals("APPLIED", results.ingest(request).disposition());
        assertEquals("DUPLICATE", results.ingest(request).disposition());
        assertEquals(1, scalar("SELECT status FROM t_submission WHERE id = 99"));
        assertEquals(12, scalar("SELECT run_time FROM t_submission WHERE id = 99"));
        assertEquals(2048, scalar("SELECT memory FROM t_submission WHERE id = 99"));
        assertEquals(1, scalar("SELECT accepted_count FROM t_problem WHERE id = 42"));
        assertEquals(1, scalar("SELECT COUNT(*) FROM t_judge_result_receipt"));
        assertEquals("ACCEPTED", jdbc.queryForObject(
                "SELECT status FROM t_judge_attempt WHERE submission_id = 99 AND attempt_no = 1",
                String.class));

        assertThrows(
                JudgeResultConflictException.class,
                () -> results.ingest(accepted("different-result-id")));
        assertEquals(1, scalar("SELECT COUNT(*) FROM t_judge_result_receipt"));
        assertEquals(1, scalar("SELECT accepted_count FROM t_problem WHERE id = 42"));
    }

    @Test
    void concurrentRedeliveryAppliesOnceAndReturnsOneDuplicate() throws Exception {
        CountDownLatch ready = new CountDownLatch(2);
        CountDownLatch start = new CountDownLatch(1);
        ExecutorService pool = Executors.newFixedThreadPool(2);
        try {
            List<Future<String>> calls = List.of(
                    pool.submit(() -> ingestAfterBarrier(ready, start)),
                    pool.submit(() -> ingestAfterBarrier(ready, start)));
            ready.await(5, TimeUnit.SECONDS);
            start.countDown();

            List<String> dispositions = calls.stream().map(this::await).sorted().toList();
            assertEquals(List.of("APPLIED", "DUPLICATE"), dispositions);
            assertEquals(1, scalar("SELECT accepted_count FROM t_problem WHERE id = 42"));
            assertEquals(1, scalar("SELECT COUNT(*) FROM t_judge_result_receipt"));
        } finally {
            pool.shutdownNow();
        }
    }

    @Test
    void partialOIScoreIsValidatedAndCommittedAtomically() throws Exception {
        jdbc.update(
                "UPDATE t_problem_version SET judge_config_json = ? WHERE id = 101",
                "{\"specialJudge\":false,\"specialJudgeCode\":null,"
                        + "\"specialJudgeLanguage\":null,\"judgeMode\":1}");
        JudgeResultRequest request = accepted("oi-result");
        request.setStatus("WRONG_ANSWER");
        request.setScore(70);
        request.setTotalScore(100);

        assertEquals("APPLIED", results.ingest(request).disposition());
        assertEquals(3, scalar("SELECT status FROM t_submission WHERE id = 99"));
        assertEquals(70, scalar("SELECT score FROM t_submission WHERE id = 99"));
        assertEquals(0, scalar("SELECT accepted_count FROM t_problem WHERE id = 42"));
        String payload = jdbc.queryForObject(
                "SELECT result_json FROM t_judge_attempt WHERE submission_id = 99 AND attempt_no = 1",
                String.class);
        JsonNode result = objectMapper.readTree(payload);
        if (result.isTextual()) {
            result = objectMapper.readTree(result.textValue());
        }
        assertEquals(70, result.path("score").asInt());
        assertEquals(100, result.path("totalScore").asInt());
    }

    private String ingestAfterBarrier(CountDownLatch ready, CountDownLatch start) throws Exception {
        ready.countDown();
        start.await(5, TimeUnit.SECONDS);
        return results.ingest(accepted("concurrent-result")).disposition();
    }

    private String await(Future<String> call) {
        try {
            return call.get(10, TimeUnit.SECONDS);
        } catch (Exception exception) {
            throw new AssertionError("concurrent ingestion failed", exception);
        }
    }

    private int scalar(String sql) {
        return jdbc.queryForObject(sql, Integer.class);
    }

    private JudgeResultRequest accepted(String resultId) {
        JudgeResultRequest request = new JudgeResultRequest();
        request.setResultId(resultId);
        request.setSubmissionId(99L);
        request.setAttemptNo(1);
        request.setStatus("ACCEPTED");
        request.setExitCode(0);
        request.setTimeUsedMillis(12);
        request.setMemoryUsedKb(2048);
        request.setStdout("ok\n");
        request.setStderr("");
        request.setCompileError("");
        return request;
    }
}
