package com.zephyr.croj.community;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

import com.zephyr.croj.common.exception.BusinessException;
import com.zephyr.croj.model.dto.CreateForumPostDTO;
import com.zephyr.croj.model.entity.User;
import com.zephyr.croj.service.CommunityContentService;
import com.zephyr.croj.service.ProblemService;
import com.zephyr.croj.service.UserService;
import org.apache.rocketmq.spring.core.RocketMQTemplate;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.jdbc.Sql;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:community-content;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false",
        "spring.data.redis.password=test-only",
        "spring.mail.password=test-only",
        "jwt.secret=test-only-secret-with-at-least-32-bytes",
        "app.upload.base-dir=target/test-uploads",
        "app.outbox.enabled=false",
})
@Sql(statements = {
        "DROP TABLE IF EXISTS t_forum_comment",
        "DROP TABLE IF EXISTS t_forum_post",
        "DROP TABLE IF EXISTS t_forum_category",
        "CREATE TABLE t_forum_category (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80) NOT NULL, slug VARCHAR(80) NOT NULL, sort_order INT NOT NULL)",
        "CREATE TABLE t_forum_post (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_id BIGINT NOT NULL, author_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, content_markdown CLOB NOT NULL, content_html CLOB NOT NULL, status VARCHAR(20) NOT NULL, pinned BOOLEAN NOT NULL, locked BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
        "CREATE TABLE t_forum_comment (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL, parent_id BIGINT, author_id BIGINT NOT NULL, content_markdown CLOB NOT NULL, content_html CLOB NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
        "INSERT INTO t_forum_category (id, name, slug, sort_order) VALUES (1, 'Algorithms', 'algorithms', 10)",
})
class CommunityContentIntegrationTest {
    @Autowired private CommunityContentService content;
    @MockitoBean private UserService users;
    @MockitoBean private ProblemService problems;
    @MockitoBean private RocketMQTemplate rocketMq;

    @Test
    void postLifecyclePersistsAndSoftDeletesThroughRealMappers() {
        User author = new User();
        author.setId(7L);
        author.setUsername("ada");
        author.setRole(0);
        author.setStatus(0);
        when(users.getById(7L)).thenReturn(author);
        CreateForumPostDTO request = new CreateForumPostDTO();
        request.setCategoryId(1L);
        request.setTitle("  Monotonic queues  ");
        request.setContentMarkdown("Keep candidates ordered.");

        long id = content.createPost(request, 7L);

        assertEquals("Monotonic queues", content.getPost(id).getTitle());
        assertEquals("ada", content.getPost(id).getAuthorName());
        content.deletePost(id, 7L);
        assertThrows(BusinessException.class, () -> content.getPost(id));
    }
}
