package com.zephyr.croj.submission;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

import com.zephyr.croj.model.dto.SubmissionDTO;
import com.zephyr.croj.model.entity.Problem;
import com.zephyr.croj.model.entity.User;
import com.zephyr.croj.service.ProblemService;
import com.zephyr.croj.service.SubmissionService;
import com.zephyr.croj.service.UserService;
import org.apache.rocketmq.spring.core.RocketMQTemplate;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.jdbc.Sql;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:submission-transaction;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false",
        "spring.data.redis.password=test-only",
        "spring.mail.password=test-only",
        "jwt.secret=test-only-secret-with-at-least-32-bytes",
        "app.upload.base-dir=target/test-uploads",
        "app.outbox.enabled=false",
})
@Sql(statements = {
        "DROP TABLE IF EXISTS t_outbox_event",
        "DROP TABLE IF EXISTS t_submission",
        "CREATE TABLE t_submission (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, problem_id BIGINT NOT NULL, user_id BIGINT NOT NULL, language VARCHAR(20) NOT NULL, `code` CLOB NOT NULL, status INT NOT NULL, run_time INT, memory INT, judge_info JSON, score INT, error_message CLOB, create_time TIMESTAMP, update_time TIMESTAMP, is_deleted INT DEFAULT 0)",
        "CREATE TABLE t_outbox_event (id VARCHAR(36) PRIMARY KEY, aggregate_type VARCHAR(64) NOT NULL, aggregate_id BIGINT NOT NULL CHECK (aggregate_id < 0), event_type VARCHAR(128) NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, published_at TIMESTAMP, attempts INT DEFAULT 0, next_attempt_at TIMESTAMP, last_error VARCHAR(1000), claimed_by VARCHAR(64), claimed_at TIMESTAMP)",
})
class SubmissionTransactionIntegrationTest {

    @Autowired
    private SubmissionService submissions;

    @Autowired
    private JdbcTemplate jdbc;

    @MockitoBean
    private UserService users;

    @MockitoBean
    private ProblemService problems;

    @MockitoBean
    private RocketMQTemplate rocketMq;

    @Test
    void outboxInsertFailureRollsBackTheSubmissionInsert() {
        User user = new User();
        user.setId(7L);
        Problem problem = new Problem();
        problem.setId(42L);
        problem.setStatus(0);
        when(users.getById(7L)).thenReturn(user);
        when(problems.getById(42L)).thenReturn(problem);
        when(problems.incrementSubmitCount(42L)).thenReturn(true);
        SubmissionDTO request = new SubmissionDTO();
        request.setProblemId(42L);
        request.setLanguage("java17");
        request.setCode("class Main {}\n");

        assertThrows(RuntimeException.class, () -> submissions.submitCode(request, 7L));

        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM t_submission", Integer.class));
    }
}
